{"uuid": "49f792ad-58d9-4a91-98e5-b3e55943fdc7", "children": ["879cbf08-0755-4e5d-8079-9e7ebe339621"], "befores": [{"name": "login", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/Users/dmytro.maksymov/PycharmProjects/self/venv/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/dmytro.maksymov/PycharmProjects/self/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/dmytro.maksymov/PycharmProjects/self/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/dmytro.maksymov/PycharmProjects/self/regular/tests/test_selenium_elemental.py\", line 8, in login\n    return login_page.LoginPage(driver)\n  File \"/Users/dmytro.maksymov/PycharmProjects/self/regular/pages/login_page.py\", line 16, in __init__\n    assert self._is_displayed(self._login_form)\n"}, "start": 1614289421625, "stop": 1614289422514}], "start": 1614289421625, "stop": 1614289422518}