{"name": "test_valid_credentials_2[tomsmith-SuperSecretPassword!]", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <regular.tests.test_selenium_elemental.TestLogin object at 0x10a485d10>\ndriver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"66ee095609953b2673405fcb56b524b1\")>\n\n    @pytest.fixture\n    def login(self, driver):\n>       return login_page.LoginPage(driver)\n\nregular/tests/test_selenium_elemental.py:8: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <regular.pages.login_page.LoginPage object at 0x10a4931d0>\ndriver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"66ee095609953b2673405fcb56b524b1\")>\n\n    def __init__(self, driver):\n        self.driver = driver\n        self._visit(\"/login\")\n>       assert self._is_displayed(self._login_form)\nE       AssertionError\n\nregular/pages/login_page.py:16: AssertionError"}, "parameters": [{"name": "name", "value": "'tomsmith'"}, {"name": "passw", "value": "'SuperSecretPassword!'"}], "start": 1614289496821, "stop": 1614289496821, "uuid": "b1073406-bbb7-441a-a1db-82ffaae41193", "historyId": "350f0497bc63748b4dc4f2ccf87ae462", "testCaseId": "aeada8f6e7fcf142a4510fe1347b624e", "fullName": "regular.tests.test_selenium_elemental.TestLogin#test_valid_credentials_2", "labels": [{"name": "parentSuite", "value": "regular.tests"}, {"name": "suite", "value": "test_selenium_elemental"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "C07ZQ0G3JYVX"}, {"name": "thread", "value": "90572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "regular.tests.test_selenium_elemental"}]}