{"name": "test_valid_credentials_2[tomsmith-SuperSecretPassword!!]", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <regular.tests.test_selenium_elemental.TestLogin object at 0x10a4aa490>\ndriver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"3139f98eecf0bb57e57a6e39da7ede0f\")>\n\n    @pytest.fixture\n    def login(self, driver):\n>       return login_page.LoginPage(driver)\n\nregular/tests/test_selenium_elemental.py:8: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <regular.pages.login_page.LoginPage object at 0x10a4b4990>\ndriver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"3139f98eecf0bb57e57a6e39da7ede0f\")>\n\n    def __init__(self, driver):\n        self.driver = driver\n        self._visit(\"/login\")\n>       assert self._is_displayed(self._login_form)\nE       AssertionError\n\nregular/pages/login_page.py:16: AssertionError"}, "parameters": [{"name": "name", "value": "'tomsmith'"}, {"name": "passw", "value": "'SuperSecretPassword!!'"}], "start": 1614289498785, "stop": 1614289498785, "uuid": "1333567c-671a-4bbb-9c24-59a0cac5c664", "historyId": "5da3238454497c27d3e325f975cebbcf", "testCaseId": "aeada8f6e7fcf142a4510fe1347b624e", "fullName": "regular.tests.test_selenium_elemental.TestLogin#test_valid_credentials_2", "labels": [{"name": "parentSuite", "value": "regular.tests"}, {"name": "suite", "value": "test_selenium_elemental"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "C07ZQ0G3JYVX"}, {"name": "thread", "value": "90572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "regular.tests.test_selenium_elemental"}]}